name: Build TS3 Plugin

on: [push, workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Compile 64-bit DLL
      run: |
        cl.exe /O2 /LD /Fe:TS3_Vinni_TV_Anti_AFK.dll plugin.cpp user32.lib

    - name: Upload Finished Plugin
      uses: actions/upload-artifact@v4
      with:
        name: TS3_Vinni_TV_Anti_AFK
        path: TS3_Vinni_TV_Anti_AFK.dll
